"""add server default for routines.is_template

Revision ID: 39fd5d4402c2
Revises: f5c67b71ea1d
Create Date: 2026-09-05 21:13:00.486636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '39fd5d4402c2'
down_revision: Union[str, None] = 'f5c67b71ea1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###