"""add client_intro

Revision ID: 623b97700c07
Revises: a05161694c05
Create Date: 2026-08-11 18:37:39.276850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '623b97700c07'
down_revision: Union[str, None] = 'a05161694c05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_intro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_client_id', sa.Integer(), nullable=False),
    sa.Column('goals_text', sa.Text(), nullable=False),
    sa.Column('experience_level', sa.Enum('beginner', 'intermediate', 'advanced', name='experience_level'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_client_id'], ['coach_clients.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_client_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('client_intro')
    # ### end Alembic commands ###