"""add plan_metrics fix, one-active-plan-per-owner constraint

Revision ID: 74f009055ca2
Revises: e6b1208aaa7b
Create Date: 2026-09-06 21:09:40.496948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74f009055ca2'
down_revision: Union[str, None] = 'e6b1208aaa7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_one_active_plan_per_owner', 'plans', ['owner_id'], unique=True, postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_one_active_plan_per_owner', table_name='plans', postgresql_where=sa.text('is_active = true'))
    # ### end Alembic commands ###