"""add coach_billing and users.phone_number

Revision ID: a05161694c05
Revises: 9e5e8287252b
Create Date: 2026-08-11 16:38:42.489160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a05161694c05'
down_revision: Union[str, None] = '9e5e8287252b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_billing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coach_id', sa.Integer(), nullable=False),
    sa.Column('plan_tier', sa.Enum('free', 'paid', name='billing_tier'), nullable=False),
    sa.Column('included_slots', sa.Integer(), nullable=False),
    sa.Column('price_per_extra_client', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['coach_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('coach_id')
    )
    op.add_column('users', sa.Column('phone_number', sa.String(length=20), nullable=True))
    op.create_unique_constraint(None, 'users', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'phone_number')
    op.drop_table('coach_billing')
    # ### end Alembic commands ###