"""add is_template to routines, make assigned_to/created_by nullable

Revision ID: adebf3c643fc
Revises: 124fd623b59f
Create Date: 2026-09-05 21:04:23.283370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'adebf3c643fc'
down_revision: Union[str, None] = '124fd623b59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('is_template', sa.Boolean(), nullable=False))
    op.alter_column('routines', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('routines', 'assigned_to',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('routines', 'assigned_to',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('routines', 'created_by',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('routines', 'is_template')
    # ### end Alembic commands ###