"""add carbs/fat to daily_logs, body_measurements table, biological_sex

Revision ID: e6b1208aaa7b
Revises: 39fd5d4402c2
Create Date: 2026-09-06 11:28:50.480251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6b1208aaa7b'
down_revision: Union[str, None] = '39fd5d4402c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('neck_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('shoulder_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('chest_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('waist_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('hip_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bicep_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('thigh_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calf_cm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('body_fat_pct_manual', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_user_measurement_date')
    )
    op.add_column('daily_logs', sa.Column('carbs_g', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('daily_logs', sa.Column('fat_g', sa.Numeric(precision=6, scale=2), nullable=True))
    sa.Enum('male', 'female', name='biological_sex').create(op.get_bind(), checkfirst=True)
    op.add_column('users', sa.Column('biological_sex', sa.Enum('male', 'female', name='biological_sex'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'biological_sex')
    sa.Enum(name='biological_sex').drop(op.get_bind(), checkfirst=True)
    op.drop_column('daily_logs', 'fat_g')
    op.drop_column('daily_logs', 'carbs_g')
    op.drop_table('body_measurements')
    # ### end Alembic commands ###