"""add is_template, template_group, template_order to routines

Revision ID: f5c67b71ea1d
Revises: adebf3c643fc
Create Date: 2026-09-05 21:05:51.419964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c67b71ea1d'
down_revision: Union[str, None] = 'adebf3c643fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('routines', sa.Column('template_group', sa.String(length=100), nullable=True))
    op.add_column('routines', sa.Column('template_order', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routines', 'template_order')
    op.drop_column('routines', 'template_group')
    # ### end Alembic commands ###